import { images } from "./constants";

export const projects = [
  {
    title: "Design System Build",
    description: "Creating shared tokens and components for Do.",
    tags: ["Design", "Sprint 4"],
    members: [
      images.USER_AVATAR,
      images.USER_AVATAR,
      images.USER_AVATAR,
      images.USER_AVATAR,
      images.USER_AVATAR,
    ],
    progress: 72,
  },
  {
    title: "Marketing Campaign Launch",
    description: "Preparing launch strategy and assets for July campaign.",
    tags: ["Marketing", "Q3"],
    members: [images.USER_AVATAR, images.USER_AVATAR],
    progress: 45,
  },
  {
    title: "Mobile App Revamp",
    description: "Redesigning the mobile app UI for smoother UX.",
    tags: ["Mobile", "Redesign"],
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
    progress: 58,
  },
  {
    title: "Onboarding Flow Improvements",
    description: "Improving first-time user experience.",
    tags: ["UX", "Growth"],
    members: [images.USER_AVATAR, images.USER_AVATAR],
    progress: 89,
  },
  {
    title: "Internal Wiki Setup",
    description: "Creating an internal knowledge base for the team.",
    tags: ["Operations", "Docs"],
    members: [images.USER_AVATAR, images.USER_AVATAR],
    progress: 32,
  },
  {
    title: "Quarterly Planning",
    description: "Drafting plans and OKRs for the next quarter.",
    tags: ["Strategy", "Q4"],
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
    progress: 20,
  },
  {
    title: "New Feature Research",
    description: "Exploring potential AI integrations for Do.",
    tags: ["R&D", "Innovation"],
    members: [images.USER_AVATAR, images.USER_AVATAR],
    progress: 10,
  },
  {
    title: "Customer Feedback Loop",
    description: "Setting up channels for better customer insights.",
    tags: ["Support", "Feedback"],
    members: [images.USER_AVATAR, images.USER_AVATAR],
    progress: 64,
  },
  {
    title: "Performance Optimization",
    description: "Improving app load times and responsiveness.",
    tags: ["Engineering", "Performance"],
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
    progress: 78,
  },
  {
    title: "Do Website Refresh",
    description: "Modernizing landing page visuals and copy.",
    tags: ["Design", "Marketing"],
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
    progress: 50,
  },
];

export const squads = [
  {
    name: "Design Explorers",
    description:
      "Design-first squad focused on product visuals, UX, and brand identity.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719282/samples/landscapes/architecture-signs.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Code Crafters",
    description: "Frontend and backend engineers delivering robust features.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719285/samples/ecommerce/accessories-bag.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Hive Ops",
    description:
      "Operations and support team ensuring smooth hive functioning.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719286/samples/imagecon-group.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Growth Sprinters",
    description: "Marketing and product growth squad experimenting weekly.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719282/samples/landscapes/architecture-signs.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Bug Busters",
    description: "QA and testing squad squashing bugs like a pro.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719307/samples/man-portrait.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Storytellers",
    description: "Content creators, writers, and documentation wizards.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719303/samples/look-up.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Pixel Pushers",
    description: "Visual designers refining the tiniest UI details.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719280/samples/people/jazz.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Data Dive",
    description: "Analysts and data scientists uncovering product insights.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719281/samples/animals/three-dogs.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Launch Legends",
    description: "Product managers coordinating roadmap & releases.",
    imageUrl:
      "https://res.cloudinary.com/dmpdhnjqs/image/upload/v1695719278/samples/landscapes/girl-urban-view.jpg",
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
  {
    name: "Support Squad",
    description: "Customer happiness heroes answering tickets & feedback.",
    imageUrl: images.USER_AVATAR,
    members: [images.USER_AVATAR, images.USER_AVATAR, images.USER_AVATAR],
  },
];

export const tasks = [
  {
    id: 1,
    title: "Conduct product research",
    team: "Research Team",
    assignedTo: ["Alice", "Bob"],
    startDate: "2025-09-20",
    endDate: "2025-09-25",
    status: "done",
    stage: "Smooth",
  },
  {
    id: 2,
    title: "Draft initial wireframes",
    team: "Design Team",
    assignedTo: ["Charlie"],
    startDate: "2025-09-23",
    endDate: "2025-09-28",
    status: "done",
    stage: "Friction",
  },
  {
    id: 3,
    title: "Backend API setup",
    team: "Engineering",
    assignedTo: ["Dana", "Ethan"],
    startDate: "2025-09-26",
    endDate: "2025-10-05",
    status: "done",
    stage: "blocked",
  },
  {
    id: 4,
    title: "Prototype usability testing",
    team: "UX Research",
    assignedTo: ["Fiona"],
    startDate: "2025-09-30",
    endDate: "2025-10-03",
    status: "done",
    stage: "Smooth",
  },
  {
    id: 5,
    title: "Frontend integration",
    team: "Engineering",
    assignedTo: ["George"],
    startDate: "2025-10-01",
    endDate: "2025-10-08",
    status: "done",
    stage: "Friction",
  },
  {
    id: 6,
    title: "Setup CI/CD pipeline",
    team: "DevOps",
    assignedTo: ["Hannah"],
    startDate: "2025-10-02",
    endDate: "2025-10-06",
    status: "done",
    stage: "Smooth",
  },
  {
    id: 7,
    title: "Content creation for landing page",
    team: "Marketing",
    assignedTo: ["Ivan", "Jade"],
    startDate: "2025-10-03",
    endDate: "2025-10-07",
    status: "done",
    stage: "Smooth",
  },
  {
    id: 8,
    title: "Legal compliance review",
    team: "Legal",
    assignedTo: ["Karen"],
    startDate: "2025-10-05",
    endDate: "2025-10-09",
    status: "done",
    stage: "blocked",
  },
  {
    id: 9,
    title: "User acceptance testing",
    team: "QA",
    assignedTo: ["Leo", "Mia"],
    startDate: "2025-10-06",
    endDate: "2025-10-12",
    status: "done",
    stage: "Friction",
  },
  {
    id: 10,
    title: "Final review & sign-off",
    team: "Management",
    assignedTo: ["Nathan", "Olivia"],
    startDate: "2025-10-10",
    endDate: "2025-10-12",
    status: "done",
    stage: "Smooth",
  },
  {
    id: 11,
    title: "Payment processing",
    team: "Finance",
    assignedTo: ["Paul"],
    startDate: "2025-10-12",
    endDate: "2025-10-13",
    status: "done",
    stage: "Smooth",
  },
  {
    id: 12,
    title: "Post-project retrospective",
    team: "All Teams",
    assignedTo: ["Quinn", "Rita", "Sam"],
    startDate: "2025-10-14",
    endDate: "2025-10-15",
    status: "done",
    stage: "Friction",
  },
];

export const customerService = {
  getData() {
    return [
      {
        id: 1000,
        name: "James Butt",
        country: {
          name: "Algeria",
          code: "dz",
        },
        company: "Benton, John B Jr",
        date: "2015-09-13",
        status: "unqualified",
        verified: true,
        activity: 17,
        representative: {
          name: "Ioni Bowcher",
          image: "ionibowcher.png",
        },
        balance: 70663,
      },
      {
        id: 1001,
        name: "Josephine Darakjy",
        country: {
          name: "Egypt",
          code: "eg",
        },
        company: "Chanay, Jeffrey A Esq",
        date: "2019-02-09",
        status: "proposal",
        verified: true,
        activity: 0,
        representative: {
          name: "Amy Elsner",
          image: "amyelsner.png",
        },
        balance: 82429,
      },
      {
        id: 1002,
        name: "Art Venere",
        country: {
          name: "Panama",
          code: "pa",
        },
        company: "Chemel, James L Cpa",
        date: "2017-05-13",
        status: "qualified",
        verified: false,
        activity: 63,
        representative: {
          name: "Asiya Javayant",
          image: "asiyajavayant.png",
        },
        balance: 28334,
      },
      {
        id: 1003,
        name: "Lenna Paprocki",
        country: {
          name: "Slovenia",
          code: "si",
        },
        company: "Feltz Printing Service",
        date: "2020-09-15",
        status: "new",
        verified: false,
        activity: 37,
        representative: {
          name: "Xuxue Feng",
          image: "xuxuefeng.png",
        },
        balance: 88521,
      },
      {
        id: 1004,
        name: "Donette Foller",
        country: {
          name: "South Africa",
          code: "za",
        },
        company: "Printing Dimensions",
        date: "2016-05-20",
        status: "proposal",
        verified: true,
        activity: 33,
        representative: {
          name: "Asiya Javayant",
          image: "asiyajavayant.png",
        },
        balance: 93905,
      },
      {
        id: 1005,
        name: "Simona Morasca",
        country: {
          name: "Egypt",
          code: "eg",
        },
        company: "Chapman, Ross E Esq",
        date: "2018-02-16",
        status: "qualified",
        verified: false,
        activity: 68,
        representative: {
          name: "Ivan Magalhaes",
          image: "ivanmagalhaes.png",
        },
        balance: 50041,
      },
      {
        id: 1006,
        name: "Mitsue Tollner",
        country: {
          name: "Paraguay",
          code: "py",
        },
        company: "Morlong Associates",
        date: "2018-02-19",
        status: "renewal",
        verified: true,
        activity: 54,
        representative: {
          name: "Ivan Magalhaes",
          image: "ivanmagalhaes.png",
        },
        balance: 58706,
      },
      {
        id: 1007,
        name: "Leota Dilliard",
        country: {
          name: "Serbia",
          code: "rs",
        },
        company: "Commercial Press",
        date: "2019-08-13",
        status: "renewal",
        verified: true,
        activity: 69,
        representative: {
          name: "Onyama Limba",
          image: "onyamalimba.png",
        },
        balance: 26640,
      },
      {
        id: 1008,
        name: "Sage Wieser",
        country: {
          name: "Egypt",
          code: "eg",
        },
        company: "Truhlar And Truhlar Attys",
        date: "2018-11-21",
        status: "unqualified",
        verified: true,
        activity: 76,
        representative: {
          name: "Ivan Magalhaes",
          image: "ivanmagalhaes.png",
        },
        balance: 65369,
      },
      {
        id: 1009,
        name: "Kris Marrier",
        country: {
          name: "Mexico",
          code: "mx",
        },
        company: "King, Christopher A Esq",
        date: "2015-07-07",
        status: "proposal",
        verified: false,
        activity: 3,
        representative: {
          name: "Onyama Limba",
          image: "onyamalimba.png",
        },
        balance: 63451,
      },
      {
        id: 1010,
        name: "Minna Amigon",
        country: {
          name: "Romania",
          code: "ro",
        },
        company: "Dorl, James J Esq",
        date: "2018-11-07",
        status: "qualified",
        verified: false,
        activity: 38,
        representative: {
          name: "Anna Fali",
          image: "annafali.png",
        },
        balance: 71169,
      },
      {
        id: 1011,
        name: "Abel Maclead",
        country: {
          name: "Singapore",
          code: "sg",
        },
        company: "Rangoni Of Florence",
        date: "2017-03-11",
        status: "qualified",
        verified: true,
        activity: 87,
        representative: {
          name: "Bernardo Dominic",
          image: "bernardodominic.png",
        },
        balance: 96842,
      },
    ];
  },
};

export const messages = [
  {
    id: 1,
    text: "Hey, how’s it going?",
    sender: "other",
    time: "Today at 2:10pm",
  },
  {
    id: 2,
    text: "All good! Just working on the project.",
    sender: "me",
    time: "Today at 2:11pm",
    status: "sent",
  },
  {
    id: 3,
    text: "Nice, what part are you on?",
    sender: "other",
    time: "Today at 2:12pm",
  },
  {
    id: 4,
    text: "Currently setting up the chat system.",
    sender: "me",
    time: "Today at 2:12pm",
    status: "delivered",
  },
  {
    id: 5,
    text: "Oh cool! Using sockets?",
    sender: "other",
    time: "Today at 2:13pm",
  },
  {
    id: 6,
    text: "Yeah, Socket.IO with Next.js 😅",
    sender: "me",
    time: "Today at 2:13pm",
    status: "read",
  },
  {
    id: 7,
    text: "That’s awesome. So Do is really coming alive 👀",
    sender: "other",
    time: "Today at 2:14pm",
  },
  {
    id: 8,
    text: "Have you handled typing indicators yet?",
    sender: "other",
    time: "Today at 2:15pm",
  },
  {
    id: 9,
    text: "Yep, just finished that earlier. Super smooth experience now.",
    sender: "me",
    time: "Today at 2:16pm",
    status: "read",
  },
  {
    id: 10,
    text: "🔥🔥🔥",
    sender: "other",
    time: "Today at 2:16pm",
  },
  {
    id: 11,
    text: "Haha thanks 😂",
    sender: "me",
    time: "Today at 2:17pm",
    status: "read",
  },
  {
    id: 12,
    text: "When do you think it’ll be ready?",
    sender: "other",
    time: "Today at 2:17pm",
  },
  {
    id: 13,
    text: `Probably by the end of the week.  
But I’m not 100% sure, I have an engagement over the weekend.`,
    sender: "me",
    time: "Today at 2:18pm",
    status: "read",
  },
  {
    id: 14,
    text: "That’s fast! 🚀",
    sender: "other",
    time: "Today at 2:18pm",
  },
  {
    id: 15,
    text: `Yeah, trying to stay productive 😅.  
The core features are ready — task creation, real-time updates, and chat.  
Now polishing the UX so Do feels different from Trello or Notion.`,
    sender: "me",
    time: "Today at 2:19pm",
    status: "read",
  },
  {
    id: 16,
    text: "Respect 👏. Honestly, the chat integration is such a game changer.",
    sender: "other",
    time: "Today at 2:20pm",
  },
  {
    id: 17,
    text: "Appreciate it bro!",
    sender: "me",
    time: "Today at 2:20pm",
    status: "read",
  },
  {
    id: 18,
    text: "What’s the idea behind Do again? Is it just tasks?",
    sender: "other",
    time: "Today at 2:21pm",
  },
  {
    id: 19,
    text: `Not just tasks.  
The goal is to make productivity feel less like a checklist and more like a **conversation**.  

So tasks, chats, notes, and even progress timelines live in one place.  
People shouldn’t need to jump between Slack, Trello, and Google Docs.`,
    sender: "me",
    time: "Today at 2:22pm",
    status: "read",
  },
  {
    id: 20,
    text: "Later!",
    sender: "other",
    time: "Today at 2:23pm",
    quote:
      "Not just tasks. The goal is to make productivity feel less like a checklist...",
  },
  {
    id: 21,
    text: "Exactly. That’s why Do exists 🙌",
    sender: "me",
    time: "Today at 2:24pm",
    status: "read",
    quote: "What’s the idea behind Do again? Is it just tasks?",
  },
];
